### ISSUE TITLE
reportException with params

### ISSUE THREAD

**Issue by wesleym** [rollbar/rollbar-android#18]
Please consider addding a reportException method to Rollbar and Notifier that also accepts additional params. Specifically, a method with signature would be perfect:

    void reportException(Throwable throwable, String level, String description, Map<String, String> params);

Sometimes, it's handy to have extra metadata related to a caught exception. Right now, it's hard to both report an exception (and take advantage of Notifier's exception processing logic) while also adding additional metadata. Adding this to the description is not ideal.

**Comment by mpj** [comment]
+1 on this. Really weird that this option isn't there.

**Comment by FnTm** [comment]
@wesleym Is there currently an easy way to pass a description along with an uncaught exception? It seemed from your answer that you were doing this.

**Comment by Crisfole** [comment]
Roger that. Sorry it's taken us so long to respond. At some point I'm looking to make rollbar-android depend on `com.rollbar.rollbar` so that this is automatically there...

**Comment by mpj** [comment]
@Crisfole is this getting any fix soon? If not, is there a workaround? I'm doing hacks like these for this now and it's driving me up the wall every single time, cause they are pretty hard to match up in the Rollbar interface.
<img width="709" alt="screenshot 2016-04-14 08 16 16" src="https://cloud.githubusercontent.com/assets/17815/14521295/f0e380d4-0228-11e6-8e4d-241b2fb4a781.png">

**Comment by Crisfole** [comment]
@mpj *ick* sorry!

For now the best fix would be to use `com.rollbar`, `rollbar`, `0.5.0` (although some bug fixes are still pending a release). I'll look into this later today.

**Comment by mpj** [comment]
@Crisfole is this fixed?

**Comment by mpj** [comment]
@Crisfole I have submitted a PR, please provide feedback if any,

**Comment by Crisfole** [comment]
@dlsteuer can you take a peek?

@mpj I'm no longer with Rollbar (although I'm still an *enormous* fan!)
