### ISSUE TITLE
Add to gradle repository

### ISSUE THREAD

**Issue by rephiscorth** [rollbar/rollbar-android#21]
Let us get it through gradle repository. It's better than having to commit jar file to version control.

**Comment by Crisfole** [comment]
Hey there, it's up on Maven: `compile 'com.rollbar:rollbar-android:0.1.3'`

**Comment by rephiscorth** [comment]
Oh thank you, my bad. Can it be added to README file?

**Comment by Crisfole** [comment]
Sure thing!
