### ISSUE TITLE
Deadlock in uncaught exception handling 

### ISSUE THREAD

**Issue by eyalgu** [rollbar/rollbar-android#23]
I'm getting a deadlock from Rollbar when 2 exceptions are thrown form 2 different threads (a scheduler thread and the main thread). as you can see from the jstack dump, RollbarThread is waiting on the condition but the main thread is already trying to join it.

Note: the deadlock happens on startup (but after the library has been initialized) so it's possible that's it's a race condition with your init flow. (perhaps the interupt is sent to the RollbarThread before it actually starts and thus is lost?).

[traces.txt](https://github.com/rollbar/rollbar-android/files/258120/traces.txt)

**Comment by dlsteuer** [comment]
Hi @eyalgu I'm trying to track this down and get it fixed.  A couple of questions for you, first does this happen reliably for you, and secondly is it possible to provide a minimal example where you are experiencing it. I was unable to replicate in my own applications.

**Comment by brianr** [comment]
@eyalgu Ping? :)

**Comment by c3ph3us** [comment]
have already a very simple solution for this and will implement it in my fork shortly :) to avoid such situations...  i see lots of thing that can be improve here :imp:

**Comment by ezarowny** [comment]
@c3ph3us can you make a pull request with your changes? I'd love to see them 👍
