### ISSUE TITLE
 No se como termine aquí buscando arreglar problemas de w7 que no encontraba certificados,  sincronizado con móvil los tengo a los dos siempre hechos una patata. Creo recordar ie no voy a sincronizar nunca más nada, no puedes fiarte de lo que guarda automático.  Lo que quiera

### ISSUE THREAD

**Issue by Akufenos** [rollbar/rollbar-android#36]

**Comment by Akufenos** [comment]
El otro día pregunte por los problemas y porque soy inútil con estos trastos y esto de la consola ni recuerdo cuando se me abrió por primera vez pero seguro que si toco algo lo jodo, así que solo quería que los creativo Compone no estén alterados porque en una actualización de móvil no había manera de cargar los permisos y lo he reiniciado un par de veces y no tiene la misma apariencia que antes lo de los certificados y el ordenador se instalaron fuentes de nuevo pero al compartir disco duro externo ha cambiado administración y otra vez hay cosas sin acceso. Hace año y medio puse m cuenta Google de respaldo en trabajo porque aún no teníamos cuenta de empresa.  Caos... Dos servidores Vpn, la cuenta Outlook me la interpretaba como exchange y me parece que ya no hay problema ahí pero creo que hubo administración externa y me aparecen cuentas de usuario que no tienen nombre solo código y algunas desaparecen pero otras es imposible saber que tipo de cuenta es. Busco una solución para inútiles, un autorun o similar porque en mayo hice la reinstalacion y conseguí abrir disco duro que el técnico no conseguía acceso pero creo que es lo que ha contaminado el resto. GRACIAS,  perdonen las molestias pero es increíble que me deje entrar  hasta aquí un lugar para desarrolladores, podría volcar un error-virus estúpido sin saber y liarla gorda,  es más el móvil creo que pone cc2 y aquí leo todo el tiempo cc 4, no he pagado nada, ni se como me dirigió Google hasta Google suite cuando en diciembre de 2016 se bloquearon muchas cuentas. Hay tanta letra que da opciones pero no soluciona nada que al que no sabe le hace la cabeza punto de nieve. Tampoco Google Suite es para usuarios particulares, el hecho es que creo haber tocado algo porque no se lo que significa todo lo que veo aquí, y no voy a hacer un máster  para ponerme al día.  Repito vía escritorio remoto o algún directorio o lo que sea que ponga a rular esto sin ningún experimento?

**Comment by coryvirok** [comment]
Hi Akufenos,

Our Spanish speaking team is having a difficult time understanding the issue that you are describing but it doesn't appear to necessarily be an issue with the rollbar-android SDK. If you can provide some more information about the bug you are seeing along with any code/logs which could help us understand that would be useful. Otherwise, I'd recommend checking out our docs here: https://rollbar.com/docs/notifier/rollbar-android/

**Comment by Akufenos** [comment]
Thank you, mi english is Worse.,  i had some difficulties about the Google counts thathi senda me to an app thats not for me. I dont know nothing about console and i cannot understand If a code is well or a comand  is valid to an action. I cannot to Mark or envoy an error thats i cant see, i cannot reach or selectIf i cannot use that. I only can note the diference. The screen's in Pc change for example .




F Pablo Gómez Lara

________________________________
