### ISSUE TITLE
Make rollbar-android available through Maven central?

### ISSUE THREAD

**Issue by daj** [rollbar/rollbar-android#9]
When using Gradle, you can specify dependencies to be downloaded from Maven Central automatically, e.g.

```
buildscript {
    repositories {
        mavenCentral()
    }
<snip>

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.squareup.retrofit:retrofit:1.6.0'
```

In the above example, here's where the artifact is hosted:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.squareup.retrofit%22%20AND%20a%3A%22retrofit%22

Most developers using Android Studio define their dependencies like this, so it would be helpful if Rollbar was available in the same way.  Thanks!

**Comment by lnikkila** [comment]
+1!

**Comment by syrnick** [comment]
+1

**Comment by brianr** [comment]
Hey everyone - wow, this has been here a while! Just wanted to update to say this is actually on our radar now. We'll write back when we have an update, either next week or the week after.

**Comment by gkaffka** [comment]
+1

**Comment by kshep** [comment]
Do you folks need it on Maven Central, specifically, or will...

https://bintray.com/rollbar/maven/rollbar-android/0.1.2

...do the trick?

**Comment by xCatG** [comment]
@kshep yes, Gradle's Android plugin also supports fetching from jCenter (which is bintray).  Thank you!

**Comment by syrnick** [comment]
The UI says 0.1.3 is available, but it's not on bintray https://www.evernote.com/l/ABPx74pOXuNLzYb6V3n4gyI5H1Dc8LYBp7E . Is the plan to push there?

**Comment by kshep** [comment]
@syrnick (Hiya Alex!),

Version 0.1.3 adds nothing but metadata for Maven Central, but we got bogged down in the logistics of deploying to Maven Central and haven't done so yet. There's really no reason at all go from 0.1.2 to 0.1.3, and we may just try to remove the 0.1.3 tag to avoid confusion... although that might cause even more confusion if/when we do eventually release 0.1.3.

**Comment by mpj** [comment]
+1. It's so 1999 that I have to download a Jar for this.

**Comment by ccabanero** [comment]
+1.  Would prefer to add rollbar to Android Studio as a dependency in my gradle file.  Thanks!!!

**Comment by snkashis** [comment]
Is this still a WIP? would like to use with Android Studio as well.

**Comment by FnTm** [comment]
+1 Any progress on this?

**Comment by Crisfole** [comment]
If a few of you wouldn't mind trying this we can close this out! :sunglasses::

groupId: `com.rollbar`
artifactId: 'android-rollbar`
version: `0.1.3`

**Comment by Crisfole** [comment]
Please re-open if the artifact was *not* in fact successfully or correctly deployed.

**Comment by patriciali** [comment]
it doesn't seem to work for me. I'm doing

`compile 'com.rollbar:android-rollbar:0.1.3'` and get error `Failed to resolve`.

**Comment by maurizi** [comment]
@Crisfole It looks like you uploaded it with a different `artifactId`? https://bintray.com/bintray/jcenter/com.rollbar%3Arollbar-android/view is `rollbar-android`, not `android-rollbar`...

**Comment by arriolac** [comment]
This worked for me instead: `compile 'com.rollbar:rollbar-android:0.1.3'`

**Comment by Crisfole** [comment]
@maurizi Thanks! I mis-typed that.
@patriciali  could you try again with the correct artifactId? I got it backwards when I typed it manually.
@arriolac Thanks!
